#!/bin/bash
date=$(date | awk '{print $1,$2,$3}')
date2=$(date +%b-%d-%Y | tr "-" " " ) #to compare expired token
commit="update $date"
expiredToken=$(cat ~/Documents/token_github.txt | tr "-" " " | awk '{print $2,$3,$4}')
token=$(cat ~/Documents/token_github.txt | tr "-" " " | awk '{print $1}')
dir=$(pwd | sed 's#/# #g')
col=$(echo $dir | wc | awk '{print $2}')
repo=$(echo $dir | awk '{print $NF}')

linkGithub="https://theman49:$token@github.com/theman49/$repo.git"

git status
echo "expired token : $expiredToken"

if [[ $date2 != $expiredToken ]]
then
	echo -n "push ? (y/n) : "
	read confirm

	if [ $confirm = 'y' -o $confirm = 'Y' ]
	then
		git add .
		git commit -m "$commit"
		git push $(echo $linkGithub) 
	fi
else
	notify-send "Token Expired"
	echo "Token Expired"
fi



