#!/bin/sh
date=$(date | awk '{print $1,$2,$3}')
commit="update $date"
token=$(cat ~/Documents/token_github.txt)
dir=$(pwd | sed 's#/# #g')
col=$(echo $dir | wc | awk '{print $2}')
repo=$(echo $dir | awk '{print $NF}')

linkGithub="https://theman49:$token@github.com/theman49/$repo.git"

git status
echo -n "push ? (y/n) : "
read confirm

if [ $confirm = 'y' -o $confirm = 'Y' ]
then
	git add .
	git commit -m "$commit"
	git push $(echo $linkGithub) 
fi



